/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_balinhui_fpaplayer_nativeapis_Win32 */

#ifndef _Included_org_balinhui_fpaplayer_nativeapis_Win32
#define _Included_org_balinhui_fpaplayer_nativeapis_Win32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_balinhui_fpaplayer_nativeapis_Win32
 * Method:    applyWindowsEffect
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_balinhui_fpaplayer_nativeapis_Win32_applyWindowsEffect
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
