/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_balinhui_fpaplayer_nativeapis_Global */

#ifndef _Included_org_balinhui_fpaplayer_nativeapis_Global
#define _Included_org_balinhui_fpaplayer_nativeapis_Global
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_balinhui_fpaplayer_nativeapis_Global
 * Method:    getHwnd
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_balinhui_fpaplayer_nativeapis_Global_getHwnd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_balinhui_fpaplayer_nativeapis_Global
 * Method:    chooseFiles
 * Signature: (JLjava/util/List;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_balinhui_fpaplayer_nativeapis_Global_chooseFiles
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_balinhui_fpaplayer_nativeapis_Global
 * Method:    messageOf
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_balinhui_fpaplayer_nativeapis_Global_messageOf
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
